apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twitter
  description: Twitter API v2
  tags:
    - twitter
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: ./twitter.oas.yaml